import type { Metadata } from "next";
import '@mantine/core/styles.css';
import { ColorSchemeScript, createTheme, MantineProvider } from "@mantine/core";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <head>
        <ColorSchemeScript defaultColorScheme="auto" />
      </head>
      <body>
        <MantineProvider defaultColorScheme="auto">
          <div>{children}</div>
        </MantineProvider>
      </body>
    </html>
  );
}
